name: Variable Management Using GH CLI

on: workflow_dispatch

jobs:
  read_variable_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh variable list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

