name: Variable Management Using GH CLI

on: workflow_dispatch



jobs:
  print_runs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: "Print number of runs of this workflow"
        run: gh variable list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
