name: Variable Management Using GH CLI

on: workflow_dispatch



jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue create --title "My new issue" --body "Here are more details."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

