# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      workflow-result-success:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'The result of the workflow: success or failure'
        # Default value if no value is explicitly provided
        default: true
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: boolean

jobs:
  failure:
    if: ${{ inputs.workflow-result}} == false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"
