name: Variable Management Workflow

on: workflow_dispatch

jobs:
  print_runs:
    runs-on: ubuntu-latest
    steps:
      - name: "Print number of runs of this workflow"
        run: echo "This workflow has run $env.NUMBER_OF_RUNS times."
