name: Variable Management Workflow

on: workflow_dispatch

env:
  NUMBER_OF_RUNS: ${{ vars.NUMBER_OF_RUNS }}

jobs:
  print_runs:
    runs-on: ubuntu-latest
    steps:
      - name: "Print number of runs of this workflow"
        run: echo "This workflow has run $NUMBER_OF_RUNS times."
      - name: "Set variable"
        # run: export NUMBER_OF_RUNS=$((NUMBER_OF_RUNS+1))
        run: export NUMBER_OF_RUNSS=5
      - name: "Print number of runs after increase"
        run: echo "This workflow has run $NUMBER_OF_RUNSS times."
